// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_hardware_revision_string         16
#define gattdb_firmware_revision_string         18
#define gattdb_battery_level                   21
#define gattdb_characteristic_presentation_format         22
#define gattdb_soil_moisture                   26
#define gattdb_battery_voltage                 28
#define gattdb_battery_low                     30
#define gattdb_temperature                     32
#define gattdb_reset                           34
#define gattdb_disconnect                      36
#define gattdb_ota_control                     39

#endif
