/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_manufacturer_name                8
#define gattdb_model_number                    10
#define gattdb_battery_level                   13
#define gattdb_battery_voltage                 17
#define gattdb_battery_low                     21
#define gattdb_reset                           24
#define gattdb_disconnect                      27

#endif
