/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#include <stdint.h>
#include "bg_gattdb_def.h"

#ifdef __GNUC__
#define GATT_HEADER(F) F __attribute__ ((section (".gatt_header"))) 
#define GATT_DATA(F) F __attribute__ ((section (".gatt_data"))) 
#else
#ifdef __ICCARM__
#define GATT_HEADER(F) _Pragma("location=\".gatt_header\"") F 
#define GATT_DATA(F) _Pragma("location=\".gatt_data\"") F 
#else
#define GATT_HEADER(F) F 
#define GATT_DATA(F) F 
#endif
#endif

GATT_DATA(const uint16_t bg_gattdb_uuidtable_16_map [])=
{
    0x2800,
    0x2801,
    0x2803,
    0x1800,
    0x2a00,
    0x2a01,
    0x180a,
    0x2a29,
    0x2a24,
    0x180f,
    0x2a19,
    0x2901,
    0x2902,
};

GATT_DATA(const uint8_t bg_gattdb_uuidtable_128_map [])=
{
0xde, 0x74, 0x2d, 0xf0, 0x70, 0x13, 0x12, 0xb5, 0x44, 0x4b, 0xb1, 0xc5, 0x20, 0xff, 0x95, 0xa4, 
0x12, 0x96, 0x49, 0xb6, 0xb6, 0x56, 0x22, 0xae, 0xe6, 0x11, 0x11, 0x86, 0xee, 0x6a, 0xfd, 0xd8, 
0x13, 0x96, 0x49, 0xb6, 0xb6, 0x56, 0x22, 0xae, 0xe6, 0x11, 0x11, 0x86, 0xee, 0x6a, 0xfd, 0xd8, 
0xdf, 0x74, 0x2d, 0xf0, 0x70, 0x13, 0x12, 0xb5, 0x44, 0x4b, 0xb1, 0xc5, 0x21, 0xff, 0x95, 0xa4, 
0xff, 0x74, 0x2d, 0xf0, 0x70, 0x13, 0x12, 0xb5, 0x44, 0x4b, 0xb1, 0xc5, 0x21, 0xff, 0x95, 0xa4, 
};




GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_27 ) = {
	.len=10,
	.data={0x44,0x69,0x73,0x63,0x6f,0x6e,0x6e,0x65,0x63,0x74,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_26 ) = {
	.properties=0x08,
	.index=4,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_25 ) = {
	.len=19,
	.data={0x08,0x1b,0x00,0xff,0x74,0x2d,0xf0,0x70,0x13,0x12,0xb5,0x44,0x4b,0xb1,0xc5,0x21,0xff,0x95,0xa4,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_24 ) = {
	.len=14,
	.data={0x57,0x72,0x69,0x74,0x65,0x20,0x74,0x6f,0x20,0x72,0x65,0x73,0x65,0x74,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_23 ) = {
	.properties=0x08,
	.index=3,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_22 ) = {
	.len=19,
	.data={0x08,0x18,0x00,0xdf,0x74,0x2d,0xf0,0x70,0x13,0x12,0xb5,0x44,0x4b,0xb1,0xc5,0x21,0xff,0x95,0xa4,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_21 ) = {
	.len=11,
	.data={0x42,0x61,0x74,0x74,0x65,0x72,0x79,0x20,0x6c,0x6f,0x77,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_20 ) = {
	.properties=0x0a,
	.index=2,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_19 ) = {
	.len=19,
	.data={0x0a,0x15,0x00,0x13,0x96,0x49,0xb6,0xb6,0x56,0x22,0xae,0xe6,0x11,0x11,0x86,0xee,0x6a,0xfd,0xd8,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_18 ) = {
	.len=15,
	.data={0x42,0x61,0x74,0x74,0x65,0x72,0x79,0x20,0x76,0x6f,0x6c,0x74,0x61,0x67,0x65,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_16 ) = {
	.properties=0x12,
	.index=1,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_15 ) = {
	.len=19,
	.data={0x12,0x11,0x00,0x12,0x96,0x49,0xb6,0xb6,0x56,0x22,0xae,0xe6,0x11,0x11,0x86,0xee,0x6a,0xfd,0xd8,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_14 ) = {
	.len=16,
	.data={0xde,0x74,0x2d,0xf0,0x70,0x13,0x12,0xb5,0x44,0x4b,0xb1,0xc5,0x20,0xff,0x95,0xa4,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_13 ) = {
	.len=13,
	.data={0x42,0x61,0x74,0x74,0x65,0x72,0x79,0x20,0x4c,0x65,0x76,0x65,0x6c,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_12 ) = {
	.properties=0x02,
	.index=0,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_11 ) = {
	.len=5,
	.data={0x02,0x0d,0x00,0x19,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_10 ) = {
	.len=2,
	.data={0x0f,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_9 ) = {
	.len=2,
	.data={0x76,0x33,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_8 ) = {
	.len=5,
	.data={0x02,0x0a,0x00,0x24,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_7 ) = {
	.len=18,
	.data={0x43,0x61,0x74,0x6e,0x69,0x70,0x20,0x45,0x6c,0x65,0x63,0x74,0x72,0x6f,0x6e,0x69,0x63,0x73,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_6 ) = {
	.len=5,
	.data={0x02,0x08,0x00,0x29,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_5 ) = {
	.len=2,
	.data={0x0a,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_4 ) = {
	.len=1,
	.data={0x00,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_3 ) = {
	.len=5,
	.data={0x02,0x05,0x00,0x01,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_2 ) = {
	.len=11,
	.data={0x44,0x65,0x6d,0x6f,0x20,0x64,0x65,0x76,0x69,0x63,0x65,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_1 ) = {
	.len=5,
	.data={0x02,0x03,0x00,0x00,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_0 ) = {
	.len=2,
	.data={0x00,0x18,}
};
GATT_DATA(const struct bg_gattdb_attribute bg_gattdb_attributes_map[])={
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_0},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_1},
    {.uuid=0x0004,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_2},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_3},
    {.uuid=0x0005,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_4},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_5},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_6},
    {.uuid=0x0007,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_7},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_8},
    {.uuid=0x0008,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_9},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_10},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_11},
    {.uuid=0x000a,.permissions=0x801,.datatype=0x07,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_12},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_13},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_14},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_15},
    {.uuid=0x8001,.permissions=0x801,.datatype=0x07,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_16},
    {.uuid=0x000c,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x01,.index=0x01,.clientconfig_index=0x00}},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_18},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_19},
    {.uuid=0x8002,.permissions=0x803,.datatype=0x07,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_20},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_21},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_22},
    {.uuid=0x8003,.permissions=0x802,.datatype=0x07,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_23},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_24},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_25},
    {.uuid=0x8004,.permissions=0x802,.datatype=0x07,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_26},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_27},
};

GATT_DATA(const uint16_t bg_gattdb_attributes_dynamic_mapping_map[])={
	0x000d,
	0x0011,
	0x0015,
	0x0018,
	0x001b,
};

GATT_DATA(const uint8_t bg_gattdb_adv_uuid16_map[])={0x00, 0x18, };
GATT_DATA(const uint8_t bg_gattdb_adv_uuid128_map[])={0x0};
GATT_HEADER(const struct bg_gattdb_def bg_gattdb_data )={
    .attributes=bg_gattdb_attributes_map,
    .attributes_max=28,
    .uuidtable_16_size=13,
    .uuidtable_16=bg_gattdb_uuidtable_16_map,
    .uuidtable_128_size=5,
    .uuidtable_128=bg_gattdb_uuidtable_128_map,
    .attributes_dynamic_max=5,
    .attributes_dynamic_mapping=bg_gattdb_attributes_dynamic_mapping_map,
    .adv_uuid16=bg_gattdb_adv_uuid16_map,
    .adv_uuid16_num=1,
    .adv_uuid128=bg_gattdb_adv_uuid128_map,
    .adv_uuid128_num=0,
};

const struct bg_gattdb_def *bg_gattdb=&bg_gattdb_data;
